version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    groups:
      version-update:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      security-update:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
